### ISSUE TITLE
Topologise Fail

### ISSUE THREAD

**Issue by Sinasta** [brunopostle/homemaker-addon#17]
whenever i click topologise there is this error:
Python: Traceback (most recent call last):
  File "/home/sinasta/.config/blender/3.1/scripts/addons/homemaker-addon-main/__init__.py", line 97, in execute
    bpy.data.collections[0].objects.link(new_object)
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1

maybe it is related to the fact that i use blender 3.1 alpha?

**Comment by brunopostle** [comment]
This line is adding the new mesh to the first blender collection in the current blender project.

Possibly the blender API has changed and the collections can't be accessed as a list any more.

..or it could be that there are no collections in the blender project - do you see any collections in the sidebar?

**Comment by Sinasta** [comment]
your second assumption was right. Sorry to have bothered you. i thought scene collection would be enough for it to work. It works perfectly fine aslong as the objects are in the same collection
