### ISSUE TITLE
activation problem

### ISSUE THREAD

**Issue by Sinasta** [brunopostle/homemaker-addon#2]
While trying to activate the addon in Belnder after installation it asks for molior and topologist. This is easyly fixed by copy pasting those two folders from the zip to the addon folder in blender. So it is not an Issue but can maybe optimised. Otherwise your addon works great. I am running Blender 2.93 alpha on manjaro linux (arch) with python 3.9.2. If you would like me to do some beta tests i would gladly help. By the way could you maybe tell me how to assign different materials for different architectural styles and how i can add those objects defining stairs, bedroom, living room etc. Thank you

**Comment by brunopostle** [comment]
Glad it works, I have to admit that I have never tried installing it through the Blender preferences. It should be possible to point Blender at the zip downloaded from github, so I need to fix this.

There are just two styles in addition to 'default': 'courtyard' and 'fancy', They are assigned by setting the blender material for individual faces in the initial mesh, just create a material and name it 'courtyard'. These styles are defined in the 'auto/Molior' folder installed by the Molior perl module. I'm currently in the process of moving some of this into the python module, I'm planning that it keeps working as I do this.

The widgets for setting room types are in [urb/examples/topologist-widgets.blend](https://bitbucket.org/brunopostle/urb/src/master/examples/topologist-widgets.blend), though with the new addon any mesh with a name beginning with bedroom|circulation|stair|kitchen|living|retail|sahn|toilet will perform the same function, i.e. a mesh named 'retail' or 'Retail.001' will be processed as a widget as long as it's centroid is within a room/space (note that currently stairs are very broken)

**Comment by Sinasta** [comment]
Thank you for your answer. Everything is working fine now. I only have the problem when i run the addon on one object and than on a second one blender crashes. I don't know if it is a problem on my side or the addon. Here is the log:

/tmp/tmpepvzywdq.molior
found triangular mesh polyline
nodes: 154
triangles: 207
/tmp/tmp0mrx5g7t.ifc
Starting import process :: 0.00
Load diff :: 0.00
Purge diffs :: 0.00
Loading file :: 0.01
Setting file :: 0.00
Calculate unit scale :: 0.00
Calculate model offset :: 0.00
Set units :: 0.00
Create project :: 0.00
Create spatial hierarchy :: 0.00
Create aggregates :: 0.00
Create aggregate tree :: 0.00
Create opening collection :: 0.00
Process element filter :: 0.00
Parsing native elements :: 0.00
Create grids :: 0.00
Done creating geometry
Create native products :: 0.00
Done creating geometry
Create products :: 0.12
Create type products :: 0.00
Create annotation :: 0.00
Create structural elements :: 0.00
Placing objects in spatial tree :: 0.00
Add project to scene :: 0.00
Info: Removed 0 vertice(s)
Mesh cleaning :: 0.01
Setting default context :: 0.00
/tmp/tmp5e8_8y5b.molior
found triangular mesh polyline
nodes: 609
triangles: 498
Warning: using default for beam_ground.dxf
/tmp/tmpegm8arny.ifc
Starting import process :: 0.00
Load diff :: 0.00
Purge diffs :: 0.00
Loading file :: 0.01
Setting file :: 0.00
Calculate unit scale :: 0.00
Calculate model offset :: 0.00
Set units :: 0.00
Create project :: 0.00
Create spatial hierarchy :: 0.00
Create aggregates :: 0.00
Create aggregate tree :: 0.00
Create opening collection :: 0.00
Process element filter :: 0.00
Parsing native elements :: 0.00
Create grids :: 0.00
Done creating geometry
Create native products :: 0.00
Done creating geometry
Create products :: 0.13
Create type products :: 0.00
Create annotation :: 0.00
Create structural elements :: 0.00
Placing objects in spatial tree :: 0.00
Add project to scene :: 0.00
Info: Removed 1 vertice(s)
 Generating stack trace...
 0x00005577b8b084fe in <unknown> from blender
 0x00005577b8b08ff3 in <unknown> from blender
 0x00005577b8b092c5 in makeDerivedMesh + 0x75 from blender
 0x00005577b88c7b92 in BKE_object_handle_data_update + 0x2a2 from blender
 0x00005577b88c80a1 in BKE_object_eval_uber_data + 0x31 from blender
 0x00005577bad80ba1 in <unknown> from blender
 0x00005577bad80bf3 in <unknown> from blender
 0x00007f225938f0a6 in tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long) + 0x46 from /usr/lib/libtbb.so.2
 0x00005577bae9cce4 in <unknown> from blender
 0x00007f2259395105 in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225939543c in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225938ed97 in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225938d3e1 in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225938981c in <unknown> from /usr/lib/libtbb.so.2
 0x00007f2259389a8a in <unknown> from /usr/lib/libtbb.so.2
 0x00007f22590af299 in <unknown> from /usr/lib/libpthread.so.0
 0x00007f224f283053 in clone at :? from /usr/lib/libc.so.6
 Generating stack trace...
 0x00005577b8b084fe in <unknown> from blender
 0x00005577b8b08ff3 in <unknown> from blender
 0x00005577b8b092c5 in makeDerivedMesh + 0x75 from blender
 0x00005577b88c7b92 in BKE_object_handle_data_update + 0x2a2 from blender
 0x00005577b88c80a1 in BKE_object_eval_uber_data + 0x31 from blender
 0x00005577bad80ba1 in <unknown> from blender
 0x00005577bad80bf3 in <unknown> from blender
 0x00007f225938f0a6 in tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long) + 0x46 from /usr/lib/libtbb.so.2
 0x00005577bae9cce4 in <unknown> from blender
 0x00007f2259395105 in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225939543c in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225938ed97 in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225938d3e1 in <unknown> from /usr/lib/libtbb.so.2
 0x00007f225938981c in <unknown> from /usr/lib/libtbb.so.2
 0x00007f2259389a8a in <unknown> from /usr/lib/libtbb.so.2
 0x00007f22590af299 in <unknown> from /usr/lib/libpthread.so.0
 0x00007f224f283053 in clone at :? from /usr/lib/libc.so.6
QObject::~QObject: Timers cannot be stopped from another thread
Error: Not freed memory blocks: 192999, total unfreed memory 67.997551 MB
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.

**Comment by Sinasta** [comment]
Oh i just tested and it is crashing as well on only one object. I tried playing around with the materials set to fancy or courtyard. Sometimes it works fine and sometimes it crashes with the error above

**Comment by Sinasta** [comment]
this is another(same?) error i get while running the addon on the object in the attached blend file:
[topolohomemaker.zip](https://github.com/brunopostle/homemaker-addon/files/6215708/topolohomemaker.zip)



Read blend: /home/sinasta/Downloads/Art/topolohomemaker.blend
cleaning Sverchok cache
 Generating stack trace...
 0x00007fb8cb69f774 in <unknown> from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb69f222 in <unknown> from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb67430a in _PyEval_EvalFrameDefault + 0x47fa from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb68096a in _PyFunction_Vectorcall + 0x1aa from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb67451e in _PyEval_EvalFrameDefault + 0x4a0e from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb68096a in _PyFunction_Vectorcall + 0x1aa from /usr/lib/libpython3.9.so.1.0
 0x000055b96f893b4e in <unknown> from blender
 0x000055b96f859468 in <unknown> from blender
 0x000055b96f329e7b in <unknown> from blender
 0x000055b96f32a37c in <unknown> from blender
 0x000055b96f32a9c1 in WM_operator_name_call_ptr + 0x41 from blender
 0x000055b96fc2831b in <unknown> from blender
 0x000055b96fc3a0d9 in <unknown> from blender
 0x000055b96f32e3ab in <unknown> from blender
 0x000055b96f32eacc in <unknown> from blender
 0x000055b96f32f078 in wm_event_do_handlers + 0x298 from blender
 0x000055b96f325122 in WM_main + 0x22 from blender
 0x000055b96ef4c977 in main + 0x367 from blender
 0x00007fb8c8d36b25 in __libc_start_main + 0xd5 from /usr/lib/libc.so.6
 0x000055b96ef81c9e in _start + 0x2e from blender
 Generating stack trace...
 0x00007fb8cb69f774 in <unknown> from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb69f222 in <unknown> from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb67430a in _PyEval_EvalFrameDefault + 0x47fa from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb68096a in _PyFunction_Vectorcall + 0x1aa from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb67451e in _PyEval_EvalFrameDefault + 0x4a0e from /usr/lib/libpython3.9.so.1.0
 0x00007fb8cb68096a in _PyFunction_Vectorcall + 0x1aa from /usr/lib/libpython3.9.so.1.0
 0x000055b96f893b4e in <unknown> from blender
 0x000055b96f859468 in <unknown> from blender
 0x000055b96f329e7b in <unknown> from blender
 0x000055b96f32a37c in <unknown> from blender
 0x000055b96f32a9c1 in WM_operator_name_call_ptr + 0x41 from blender
 0x000055b96fc2831b in <unknown> from blender
 0x000055b96fc3a0d9 in <unknown> from blender
 0x000055b96f32e3ab in <unknown> from blender
 0x000055b96f32eacc in <unknown> from blender
 0x000055b96f32f078 in wm_event_do_handlers + 0x298 from blender
 0x000055b96f325122 in WM_main + 0x22 from blender
 0x000055b96ef4c977 in main + 0x367 from blender
 0x00007fb8c8d36b25 in __libc_start_main + 0xd5 from /usr/lib/libc.so.6
 0x000055b96ef81c9e in _start + 0x2e from blender
Error: Not freed memory blocks: 180483, total unfreed memory 49.953442 MB
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.

**Comment by Sinasta** [comment]
Im on manjaro linux (arch) with python 3.9.2-1 and blender 2.93 alpha with systems python.

**Comment by brunopostle** [comment]
The first crash is blenderbim failing to import the IFC file, if you haven't rebooted the IFC file should still exist in your /tmp folder, can you attach it?: /tmp/tmpegm8arny.ifc

I'm not sure about the second crash, cppyy-1.9.4 really doesn't work, I needed to upgrade to 1.9.5, what version of cppyy do you have?

**Comment by brunopostle** [comment]
The mesh in your zip file works ok for me, as you can see the stairs are a bit of mess, and the 'sahn' cell type doesn't do anything interesting (sahn is an outdoor space that forms part of the circulation of the building, basically a private courtyard, it is fully implemented in the old evolution system, but in this system it is a placeholder to remind me that it needs to work here too).

![Screenshot from 2021-03-27 18-50-36](https://user-images.githubusercontent.com/1747315/112731303-4ee79700-8f2e-11eb-90af-d1ffad1e2081.png)

**Comment by Sinasta** [comment]
Thank you for your answer. So my Cppyy version is 1.9.4 i will try to update it. I will attach the ifc and molior file from tmp:

[Ifc_molior.zip](https://github.com/brunopostle/homemaker-addon/files/6216242/Ifc_molior.zip)

**Comment by Sinasta** [comment]
i found something interesting: when i try to import the ifc file from/tmp/ to blender with blender bim, Blender crashes. But when i deactivate the flag: import and clean mesh, it imports perfectly fine. it seems that this is a blenderbim problem. Thank you for your help

**Comment by brunopostle** [comment]
I seems ok here with both settings, though I'm running a blenderbim and ifcopenshell snapshot from yesterday

**Comment by Sinasta** [comment]
I am running the latest snapshot of ifcopenshell/blender bim from today. I will investigate more
