### ISSUE TITLE
Switch to sub-classing Topologic

### ISSUE THREAD

**Issue by brunopostle** [brunopostle/homemaker-addon#32]
The Homemaker add-on ships with a module called `topologist` that provides additional methods that are not provided by the various `topologic` classes.

For instance, `import topologist.face` appends a new `topologic.Face.IsVertical()` method, which is unexpected if you think that Topologic should have its own namespace.

This behaviour made sense initially due to the way the Topologic C++ bindings were implemented, but it no longer makes any sense, Homemaker should subclass `topologic` as a normal well-behaved library should.

Classes that are overloaded like this are `Cell`, `CellComplex`, `Edge`, `Face`, `Graph`, `Topology`, and `Vertex`.

**Comment by brunopostle** [comment]
Further, Homemaker should switch to using the @wassimj / [topologicpy](https://github.com/wassimj/topologicpy) API for Topologic. There are probably also a bunch of methods in the `topologist` module that should be moved out of Homemaker and into `topologicpy`

**Comment by wassimj** [comment]
@brunopostle if you can send me a list of methods and the topologicpy class that they should belong to (e.g. Face, Cell, CellComplex), I can check them, refactor them to fit the coding style of topologicpy and start adding as appropriate. Thank you.

**Comment by brunopostle** [comment]
@wassimj The methods I add to topologic are listed here, though I suspect there are only a handful that are generically useful: https://homemaker-addon.readthedocs.io/en/latest/api-topologist.html

**Comment by wassimj** [comment]
@brunopostle thank you. Some of the methods have already been incorporated in topologicpy. Some, as you indicated, are not suitable for a general API, but will see what can be integrated. Thanks again.

**Comment by brunopostle** [comment]
I made another failed attempt to subclass the topologic python bindings, either I don't understand what I'm doing or the bindings are configured in a way that precludes subclassing.

This demonstrates my problem, basically constructors such as `ByStartVertexEndVertex()` return objects of the super class, not the subclass:

```
import topologic


class MyEdge(topologic.Edge):
    def __init__(self):
        return


foo = MyEdge

print(foo)
# <class '__main__.MyEdge'>

bar = MyEdge.ByStartVertexEndVertex(
    topologic.Vertex.ByCoordinates(0.4, -2.2, 0.3),
    topologic.Vertex.ByCoordinates(0.5, -2.4, 0.3),
)

print(bar)
# <topologic.Edge object at 0x7fb385ed6d30>

**Comment by wassimj** [comment]
You didn't override the parent method which doesn't know anything about your class so it returns whatever it always returns: a topologic.Edge. In topologicpy, I decided not to subclass from topologic. Instead it is a wrapper class that accepts and returns topologic entities and adds new methods.

Some possible ways you can subclass are listed at: https://stackoverflow.com/questions/597199/converting-an-object-into-a-subclass-in-python




Athro Wassim Jabi, Ph.D. (fe, e, ef)
Cadeirydd Dulliau Cyfrifiadurol ym maes Pensaernïaeth
Ysgol Pensaernïaeth Cymru

Prifysgol Caerdydd

Adeilad Bute

Rhodfa’r Brenin Edward VII

Caerdydd CF10 3NB

Cymru D.U.
Ffôn : +44 (0)29 2087 5981
Ebost: ***@***.******@***.***>

Professor Wassim Jabi, Ph.D. (he, his, him)
Chair of Computational Methods in Architecture
Welsh School of Architecture

Cardiff University

Bute Building
King Edward VII Avenue
Cardiff CF10 3NB
Wales U.K.
Phone: +44 (0)29 2087 5981
Email: ***@***.******@***.***>

Mae Prifysgol Caerdydd yn elusen gofrestredig. Rhif 1136855
Cardiff University is a registered charity. No 1136855



Yn falch o fod yn un o’r 3 Ysgol Pensaernïaeth orau yn y DU |The Times/The Sunday Times Good

University Guide 2023 | 4ydd yn y DU: REF 2021| Canolfan ragoriaeth sy'n arwain y byd ym meysydd pensaernïaeth a'r amgylchedd adeiledig

Prifysgol y Flwyddyn yng Nghymru 2023



Proud to be a top 3 UK School of Architecture |The Times/The Sunday Times Good University Guide 2023 | 4th in the UK: REF 2021| A world-leadingcentre of excellence for architecture

and the built environment

Welsh University of the Year 2023

________________________________

**Comment by brunopostle** [comment]
Hmm, I'm not keen on writing wrappers for every topologic method that returns topologic objects.

I'm currently doing 'python monkey patching', which works very well, but it does mean that users will see all my custom methods in the topologic namespace. I guess I shouldn't worry, this would only be a problem if a conflicting method name was added to the base library.

Closing, because migrating to topologicpy is another thing altogether.

**Comment by wassimj** [comment]
ok. But just to note that topologicpy is the future of how 3rd party python modules will interact with topologic.
