### ISSUE TITLE
Missing yaml

### ISSUE THREAD

**Issue by s-leger** [brunopostle/homemaker-addon#4]
Setup linux py39 version under blender 2.93 report a missing yaml module (pyyaml).
When pyyaml installed by hand homemaker run as expected.
Thank you for your hard work on this !

**Comment by brunopostle** [comment]
Thanks for testing, good to hear that pyyaml is all that was missing. I have created a new add-on bundle that includes pyyaml: https://github.com/brunopostle/homemaker-addon/releases/tag/2021-06-05

**Comment by s-leger** [comment]
Confirmed to work under linux Mint 20
Had to remove older one before installing this release.
