### ISSUE TITLE
No module named 'TopologicSverchok-v'

### ISSUE THREAD

**Issue by slavingia** [brunopostle/homemaker-addon#65]
Originally opened in [that repo](https://github.com/wassimj/TopologicSverchok/issues/53), but was asked to move it here:

```
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable mod = import (module name)
ModuleNotFoundError: No module named 'TopologicSverchok-v'
```

**Comment by brunopostle** [comment]
Sorry, I have no idea, 'TopologicSverchok' doesn't appear anywhere in Homemaker. The Homemaker add-on just uses the base 'topologic' library.

If you can search the 'scripts' folder and tell us which file has this "TopologicSverchok-v" text, we may be able to figure out what is responsible.

**Comment by slavingia** [comment]
I think what's happening is that it's trying to pull in Topologic by pulling in `TopologicSverchok-v.0.8.2.9` which is getting cut off to reflect the error above.

**Comment by slavingia** [comment]
Removing the library I get just `No module named 'topologic'`

**Comment by brunopostle** [comment]
I'm still but sure what is happening. I assume you are trying to run the Homemaker add-on in blender.

Have you downloaded one of the ZIP files from the Releases page and installed it in Blender > Preferences > add-ons > install ?

There are other ways to run Homemaker, but they involve finding and installing libraries, so are not recommended.

**Comment by slavingia** [comment]
Yes that’s what I tried. On MacOS.

**Comment by slavingia** [comment]
Are you saying I don’t need to independently install Topologic at all and just installing the Homemaker ZIP will be enough?

**Comment by brunopostle** [comment]
Yes, there should be a working Mac ZIP file with all dependencies (except BlenderBIM) on the releases page: https://github.com/brunopostle/homemaker-addon/releases

**Comment by slavingia** [comment]
I am getting the same error doing that:

```
Report: Error
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable mod = _import_(module_name)
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/homemaker/ init py", line 9, in <module> from topologic import Vertex, Face, CellComplex ModuleNotFoundError: No module named 'topologic'
```

I am on MacOS 13.5 Beta (22G5048d), Blender 3.5.1, and Homemaker [2023-05-29].

**Comment by brunopostle** [comment]
Do you have the right ZIP? there are two for Mac:

`blender-homemaker-2023-05-29-darwin.zip` for older macs, and `blender-homemaker-2023-05-29-darwin-arm.zip` for a newer ARM/M1/silicon mac

**Comment by slavingia** [comment]
Ah, good point. I switched to the ARM version and got this:

```
traceback most recent call last)
File "/Applications/Blender ann/Cont
mod = import (module_name
File "/Users/sahil/Librarv/Applicatior
from topologic import Vertex, Face, ImportError: dopen Users sahil/Librarv/Application Su
5/scrints/addons/homemaker/libs/site/packages/topoloaic.covthon-310-darwin.so.0x0002):Librarvnotloaded:/ont/homebrew/ont/topoloaic/lib/libTopoloaicCore.O.dvlib
Retorenced trom' < 9070828-515723351-20053120 0
Users sahil/Librarv/Application Support/Blender/ 3.5/scripts/addons/homemaker/libs/site/packages/topologic.cpvthon-310-darwin.so
Reason: tried: 'opt/homebrew/opt/topologic/lib/libTopologicCore.o.dylib'(no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/topologic/lib/libTopologicCore.0.dylib' (no such file), '/opt/homebrew/opt/topologic/lib/libTopologicCore.o.dylib" (no such file), '/usr/lib/libTopologicCore.O.dylib' (no such file, not in dyld
```

**Comment by brunopostle** [comment]
Yes, it does look like that file is missing, I'll investigate

**Comment by brunopostle** [comment]
Apologies, I don't have any way of testing these ARM packages. I copied the ARM libraries from TopologicSverchok, but although they contain the python bindings, they don't contain this libTopologicCore library :(

So it looks like the only way to run the Homemaker add-on on ARM is to download the x86 blender, blenderbim and homemaker-addon packages and run them in emulation mode (and the same applies to TopologicSverchok @wassimj?)

**Comment by wassimj** [comment]
Topologic does not yet support Apple Silicon. I hope to add that by the end of the summer

**Comment by slavingia** [comment]
Is that a small, simple enough task for an outsider to tackle? I can give it a shot earlier than that if so. I would need a bit of a scope to follow in terms of the changes you expect.

**Comment by slavingia** [comment]
Does Homemaker need TopologicSverchok at all? If we can move to pointing directly to topologicpy from this addon, instead of using TopologicCore / TopologicSverchok.

**Comment by brunopostle** [comment]
@slavingia topologicpy uses TopologicCore (at least for the time being), so it doesn't fix this ARM Apple Silicon problem.

Homemaker doesn't need TopologicSverchok, but if TopologicSverchok is installed on blender it provides a copy of TopologicCore and the python bindings, so Homemaker is able to make use of this.

The ARM TopologicCore library must have existed at some point, as it wouldn't have been possible to build the ARM version of the python bindings without it - We just don't seem to have a copy of it.
