### ISSUE TITLE
Adding new fitness function

### ISSUE THREAD

**Issue by slavingia** [brunopostle/homemaker-addon#66]
I only see one in the repo, which seems low for how powerful the software already is.

Am I missing something? Documentation on how to add a new fitness function would be great.

**Comment by brunopostle** [comment]
The Homemaker evolutionary design tool is a collection of Perl libraries hosted on Bitbucket: [urb](https://bitbucket.org/brunopostle/urb/wiki/Home) and [Homemaker](https://bitbucket.org/brunopostle/homemaker/wiki/Home).

This Homemaker-addon is effectively the post-processor half of this Perl tool that generates detailed 3D models from raw spaces, ripped-out and rewritten in Python to make use of Topologic and IfcOpenShell, so there is no evolutionary code here.

This Python code can still be used to generate 3D models for the non-interactive evolutionary tool, but it can also be used as a nice interactive pointy-clicky way to generate detailed BIM models in Blender, hence it is packaged as a Blender add-on.

However, there is nothing in this interactive tool to stop people designing awful inhuman buildings. So the plan was always to port the fitness functions from the Perl library to Python, then they can be used in the interactive tool to give people feedback while they design - This is why there is only one fitness function, porting these fitness functions is unfinished business, and the whole UI for offering this feedback in Blender hasn't even been started.

Hope this makes sense, this software is both in a useful state and in the process of becoming something else.
