### ISSUE TITLE
Python: Traceback (most recent call last) Error

### ISSUE THREAD

**Issue by NS-P6-2014** [brunopostle/homemaker-addon#7]
Hello and thanks for your beautiful work!

I've successfully installed the homemaker-addon on Blender 2.93 but when I tried to test it on the Default Cube, that mesh disappeared and leave me that message on the Info Log:

```
Python: Traceback (most recent call last):
  File "/home/administrator/.config/blender/2.93/scripts/addons/homemaker/__init__.py", line 99, in execute
    ifc = molior.ifc.init(mesh.name, elevations)
  File "/home/administrator/.config/blender/2.93/scripts/addons/homemaker/molior/ifc/__init__.py", line 52, in init
    ifc.createBuilding(site, building_name, elevations)
  File "/home/administrator/.config/blender/2.93/scripts/addons/homemaker/molior/ifc/__init__.py", line 73, in createBuilding
    run(
  File "/home/administrator/.config/blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 15, in run
    listener(usecase_path, ifc_file, settings)
  File "/home/administrator/.config/blender/2.93/scripts/addons/archipack_20/archipack_io_export_ifc2.py", line 956, in preprocess_object_placement
    o =  IfcStore.guid_map[product.GlobalId]
KeyError: '12jm9Sx019XRgpzx6qP6rc'

location: <unknown location>:-1
```

Sorry, I'm trying to learn but I'm a beginner and I can't understand what I am reading here.

Do you have any idea on how to fix this?

Thanks in advance!

**Comment by brunopostle** [comment]
It looks like there is a conflict with the archipack add-on. Can you try temporarily disabling archipack, restart blender so archipack isn't loaded, and try again?

-- 
Bruno

**Comment by NS-P6-2014** [comment]
It worked! Thank you! Archipack needed to be disabled while using the homemaker-addon.

**Comment by brunopostle** [comment]
@s-leger it looks like I've done something that conflicts with archipack here, any ideas?

**Comment by s-leger** [comment]
@brunopostle nothing wrong on your side, you simply spotted an issue in archipack's exporter. Will fix in next release, and thank for reporting.

**Comment by brunopostle** [comment]
@s-leger @Moult at this stage Homemaker hasn't done anything with blenderbim (I construct the whole IFC model using only ifcopenshell, write it to disk, discard it and then import the IFC file again using blenderbim).

I suspect the problem is that I have overloaded this createBuilding() method onto ifcopenshell.file (because I couldn't figure-out how to subclass it), basically I'm polluting the namespace.
