### ISSUE TITLE
integrate and use Corinthian type columns DXF files in Blender with Homemaker add-on

### ISSUE THREAD

**Issue by boes3d** [brunopostle/homemaker-addon#8]
Hi M Postle,
On YouTube https://youtube.com/watch?v=24PVLcGYhN0, you present matérials properties in Blender : arcade, rustic, tuscan, etc...
How can I use these matérials properties in Blender LINuX ? (I do not see in my Blender  these matérials properties)
I would like to integrate and use Corinthian type columns DXF files with your Homemaker add-on in Blender.
Is it possible ?
Can you tell me the method if possible?
Thanks in advance.
Rémy HAENEL

**Comment by brunopostle** [comment]
These styles are supplied with the add-on. You control styles by giving faces in the mesh different blender materials.

These can be any material, only the name is important, currently the styles are 'default', 'courtyard', 'fancy', 'tuscan', 'rustic' and 'arcade'.

**Comment by boes3d** [comment]
Bonsoir M Postle,Thank you very much for your prompt response. Thanks again. Best regards.Rémy HAENELenvoyé : 28 août 2021 à 17:04de : Bruno Postle ***@***.***>à : brunopostle/homemaker-addon ***@***.***>cc : boes3d ***@***.***>, Author ***@***.***>objet : Re: [brunopostle/homemaker-addon] integrate and use Corinthian type columns DXF files in Blender with Homemaker add-on (#8) These styles are supplied with the add-on. You control styles by giving faces in the mesh different blender materials.  These can be any material, only the name is important, currently the styles are 'default', 'courtyard', 'fancy', 'tuscan', 'rustic' and 'arcade'.   On 28 August 2021 14:05:08 BST, boes3d ***@***.***> wrote: >Hi M Postle, > >On YouTube https://youtube.com/watch?v=24PVLcGYhN0, you present matérials properties in Blender : arcade, rustic, tuscan, etc... > >How can I use these matérials properties in Blender LINuX ? (I do not see in my Blender these matérials properties) > >I would like to integrate and use Corinthian type columns DXF files with your Homemaker add-on in Blender. > >Is it possible ? > >Can you tell me the method if possible? > >Thanks in advance. > >Rémy HAENEL > > > >-- > >You are receiving this because you are subscribed to this thread. > >Reply to this email directly or view it on GitHub: > >https://github.com/brunopostle/homemaker-addon/issues/8—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
